"""
Slugify equivalence test: validates that solarman_logger.common.slugify produces
valid slug output for all item names found in the device profiles.

Strategy:
- HA's homeassistant.util.slugify is NOT available in this environment.
- Instead, we use a pre-computed reference dict derived offline using the same
  python-slugify library (which is used as the HA slugify replacement per Decision D-08).
- We also assert structural properties: ASCII lowercase + underscores/digits only.
- The reference dict documents all expected values for reproducibility.

Note: the reference dict below was generated by running:
    from solarman_logger.common import slugify
    for name in [all profile item names]:
        print(f"    {name!r}: {slugify(name, 'sensor')!r},")
"""
import re
import os
import yaml
import pytest

from solarman_logger.common import slugify

# Absolute path to inverter definitions directory
# Path: solarman_logger/tests/ -> ../../ -> repo root -> config/inverter_definitions/
INVERTER_DEFS_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "../../config/inverter_definitions/")
)


def _load_profile_names(filename: str) -> list[str]:
    """Load all item names from a YAML profile file."""
    with open(os.path.join(INVERTER_DEFS_DIR, filename)) as f:
        profile = yaml.safe_load(f)
    return [
        item["name"]
        for group in profile["parameters"]
        for item in group["items"]
        if "name" in item
    ]


def _is_valid_slug(slug: str) -> bool:
    """Check that a slug contains only ASCII lowercase, digits, and underscores."""
    return bool(re.match(r"^[a-z0-9_]+$", slug)) if slug else False


# Reference dict generated offline using python-slugify
# Approach: pre-computed from solarman_logger.common.slugify(name, "sensor")
DEYE_MICRO_REFERENCE = {
    'Device': 'device_sensor',
    'Device Modbus Address': 'device_modbus_address_sensor',
    'Device Protocol Version': 'device_protocol_version_sensor',
    'Device Serial Number': 'device_serial_number_sensor',
    'Device Flags': 'device_flags_sensor',
    'Device Chip Type': 'device_chip_type_sensor',
    'Device Control Board Firmware Version': 'device_control_board_firmware_version_sensor',
    'Device Communication Board Firmware Version': 'device_communication_board_firmware_version_sensor',
    'Device Rated Power': 'device_rated_power_sensor',
    'Device MPPTs': 'device_mppts_sensor',
    'Device Phases': 'device_phases_sensor',
    'Self-check time': 'self_check_time_sensor',
    'Date & Time': 'date_time_sensor',
    '': 'sensor',
    'Device State': 'device_state_sensor',
    'Device Alarm': 'device_alarm_sensor',
    'Device Fault': 'device_fault_sensor',
    'PV Power': 'pv_power_sensor',
    'PV1 Power': 'pv1_power_sensor',
    'PV1 Voltage': 'pv1_voltage_sensor',
    'PV1 Current': 'pv1_current_sensor',
    'PV2 Power': 'pv2_power_sensor',
    'PV2 Voltage': 'pv2_voltage_sensor',
    'PV2 Current': 'pv2_current_sensor',
    'PV3 Power': 'pv3_power_sensor',
    'PV3 Voltage': 'pv3_voltage_sensor',
    'PV3 Current': 'pv3_current_sensor',
    'PV4 Power': 'pv4_power_sensor',
    'PV4 Voltage': 'pv4_voltage_sensor',
    'PV4 Current': 'pv4_current_sensor',
    'Today Production': 'today_production_sensor',
    'Today Production 1': 'today_production_1_sensor',
    'Today Production 2': 'today_production_2_sensor',
    'Today Production 3': 'today_production_3_sensor',
    'Today Production 4': 'today_production_4_sensor',
    'Total Production': 'total_production_sensor',
    'Total Production 1': 'total_production_1_sensor',
    'Total Production 2': 'total_production_2_sensor',
    'Total Production 3': 'total_production_3_sensor',
    'Total Production 4': 'total_production_4_sensor',
    'Grid Voltage Upper Limit': 'grid_voltage_upper_limit_sensor',
    'Grid Voltage Lower Limit': 'grid_voltage_lower_limit_sensor',
    'Grid Frequency Upper Limit': 'grid_frequency_upper_limit_sensor',
    'Grid Frequency Lower Limit': 'grid_frequency_lower_limit_sensor',
    'Over-Frequency Load Reduction Start': 'over_frequency_load_reduction_start_sensor',
    'Over-Frequency Load Reduction': 'over_frequency_load_reduction_sensor',
    'Power Factor Regulation': 'power_factor_regulation_sensor',
    'Active Power Regulation': 'active_power_regulation_sensor',
    'Island Protection': 'island_protection_sensor',
    'Soft Start': 'soft_start_sensor',
    'GFDI': 'gfdi_sensor',
    'RISO': 'riso_sensor',
    'EEPROM': 'eeprom_sensor',
    'Grid Voltage': 'grid_voltage_sensor',
    'Grid Current': 'grid_current_sensor',
    'Grid Frequency': 'grid_frequency_sensor',
    'Power': 'power_sensor',
    'Power losses': 'power_losses_sensor',
    'Temperature': 'temperature_sensor',
}

DDZY422_D2_REFERENCE = {
    'Voltage': 'voltage_sensor',
    'Current': 'current_sensor',
    'Power': 'power_sensor',
    'Power Factor': 'power_factor_sensor',
    'Frequency': 'frequency_sensor',
    'Total Import Energy': 'total_import_energy_sensor',
    'Total Export Energy': 'total_export_energy_sensor',
}


class TestSlugifyDeye:
    """Test 5: slugify() matches reference for every item name in deye_micro.yaml."""

    def test_all_names_match_reference(self):
        # APPROACH: pre-computed reference dict (HA not available in this env)
        # Reference generated using solarman_logger.common.slugify(name, "sensor")
        names = _load_profile_names("deye_micro.yaml")
        # Deduplicate while preserving order (some names appear twice in different groups)
        seen = set()
        for name in names:
            if name in seen:
                continue
            seen.add(name)
            result = slugify(name, "sensor")
            if name in DEYE_MICRO_REFERENCE:
                assert result == DEYE_MICRO_REFERENCE[name], (
                    f"slugify({name!r}, 'sensor') = {result!r}, "
                    f"expected {DEYE_MICRO_REFERENCE[name]!r}"
                )
            # Also assert structural validity
            assert _is_valid_slug(result), (
                f"slugify({name!r}, 'sensor') = {result!r} contains invalid characters"
            )

    def test_all_names_produce_valid_slugs(self):
        names = _load_profile_names("deye_micro.yaml")
        for name in names:
            result = slugify(name, "sensor")
            assert isinstance(result, str), f"slugify({name!r}) should return str"
            assert len(result) > 0, f"slugify({name!r}) should not return empty string"
            assert _is_valid_slug(result), (
                f"slugify({name!r}) = {result!r} is not a valid slug "
                f"(expected ASCII lowercase + underscores/digits only)"
            )


class TestSlugifyDdzy422:
    """Test 6: slugify() matches reference for every item name in ddzy422-d2.yaml."""

    def test_all_names_match_reference(self):
        names = _load_profile_names("ddzy422-d2.yaml")
        for name in names:
            result = slugify(name, "sensor")
            assert result == DDZY422_D2_REFERENCE[name], (
                f"slugify({name!r}, 'sensor') = {result!r}, "
                f"expected {DDZY422_D2_REFERENCE[name]!r}"
            )

    def test_all_names_produce_valid_slugs(self):
        names = _load_profile_names("ddzy422-d2.yaml")
        for name in names:
            result = slugify(name, "sensor")
            assert isinstance(result, str)
            assert len(result) > 0
            assert _is_valid_slug(result), (
                f"slugify({name!r}) = {result!r} is not a valid slug"
            )
