# Solarman Smart Meter DDZY422-D2
#
# Reference: https://github.com/user-attachments/files/17586995/DDZY422-D2.-modbus.HT-YF2018-0929-01._1729757263801_10de75.xlsx
#

default:
  update_interval: 5
  digits: 3

parameters:
  - group: Variable Data 1
    items:
      - name: Voltage
        class: voltage
        uom: V
        scale: 0.1
        rule: 1
        registers: [0x0001]

      - name: Current
        class: current
        state_class: measurement
        uom: A
        scale: 0.001
        rule: 2
        magnitude: True
        registers: [0x0003, 0x0002]

      - name: Power
        class: power
        state_class: measurement
        uom: W
        scale: 1
        rule: 2
        magnitude: True
        registers: [0x0007, 0x0006]

      - name: Power Factor
        class: power_factor
        state_class: measurement
        scale: 0.001
        rule: 2
        magnitude: True
        registers: [0x000C]

      - name: Frequency
        class: frequency
        state_class: measurement
        uom: Hz
        scale: 0.01
        rule: 1
        registers: [0x000D]

  - group: Energy
    items:
      - name: Total Import Energy
        class: energy
        state_class: total_increasing
        uom: kWh
        scale: 0.01
        rule: 4
        registers: [0x000F, 0x000E]

      - name: Total Export Energy
        class: energy
        state_class: total_increasing
        uom: kWh
        scale: 0.01
        rule: 4
        registers: [0x0019, 0x0018]
